default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bookerka_development

test:
  <<: *default
  database: bookerka_test

production:
  <<: *default
  database: bookerka_production
